name = "furikaeri-mcp"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FurikaeriMCP"]

[durable_objects]
bindings = [
  { class_name = "FurikaeriMCP", name = "MCP_OBJECT" }
]

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "2b8d1074a09a4172908f3bd096bf40b6"

[observability]
enabled = true

[dev]
port = 8788
